FROM puckel/docker-airflow:1.10.9

ARG project_name=Mega
ENV ALDATA__ENV__PROJECT_NAME=$project_name
ENV ALDATA__ENV__DEPLOY_SOURCES=src/python/packages
ENV ALDATA__ENV__DEPLOY_DAGS=src/python/dags
ENV ALDATA__ENV__DEPLOY_SCRIPT=src/script/ci/deploy_dags.sh
ENV ALDATA__ENV__DAG_GIT=git_dag_source


USER airflow
COPY assets/airflow/entrypoint-airflow.sh /entrypoint.sh
COPY assets/airflow/requirements.txt /
COPY assets/airflow/airflow_config.sh ${AIRFLOW_HOME}/
COPY assets/airflow/*.json /

RUN mkdir -p ~/workspace/${ALDATA__ENV__PROJECT_NAME}/

USER root
RUN chmod +x /entrypoint.sh && \
    apt-get update && \
    apt-get install -y apt-transport-https libfbclient2 git zip procps telnet && \
    mkdir -p ${AIRFLOW_HOME}/dags/

COPY assets/airflow/*.py ${AIRFLOW_HOME}/dags/
RUN chown -R airflow:airflow ${AIRFLOW_HOME}/

USER airflow

VOLUME /data/airflow

# docker build -f Dockerfile-airflow -t aldata/airflow-voz .