version: '3'
services:
    postgres:
        image: postgres
        env_file: .env
        volumes:
            - ~/data/mega/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 60s
            timeout: 5s
            retries: 3

    webserver:
        image:  puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__FERNET_KEY=yKjwPsHZqm_MS7Ylqpi3IpvATp-sny5By9c3x9lekQs=
            - POSTGRES_USER=mega
            - POSTGRES_PASSWORD=Mega2021
            - POSTGRES_DB=mega
#        env_file: .env
        volumes:
            - ~/data/airflow:/data/airflow
        ports:
            - "28080:8080"
        command: webserver
        healthcheck:
            test: [ "CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]" ]
            interval: 30s
            timeout: 30s
            retries: 3
